name: readverse
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# SDK constraints
environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter-specific configuration
flutter:
  uses-material-design: true
  assets:
    - images/Readverse.jpg
    - images/rich_dad.jpg
    - images/alchemist.jpg
    - images/icon_plus.jpg